trigger:
- master


variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'cae00c10-93d7-4cb0-b141-9d475c70051c'

  # Agent VM image name
  vmImageName: 'windows-latest'

  # DEBUG
  system.debug: true


stages:

- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackage
    displayName: Maven Package
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: Copy job jar
      inputs:
        SourceFolder: 'target'
        Contents: 'learnflink-*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'
        artifactName: JobJar

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: DownloadDeploy
      displayName: Download and Deploy
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Pipeline Artifacts'
        inputs:
          artifact: 'JobJar'
          downloadPath: '$(build.artifactstagingdirectory)' 

      - task: AzureFileCopy@3
        inputs:
          sourcePath: '$(build.artifactstagingdirectory)' 
          azureSubscription: '$(azureSubscription)'
          destination: azureBlob
          storage: jqinblobstorage
          containerName: vvp
          BlobPrefix: 'artifacts/namespaces/default'

- stage: Run
  displayName: Run stage
  jobs:
    - job: Run
      steps:
        - script: echo Hello World

        - task: InvokeRESTAPI@1
          inputs:
            connectionType: 'connectedServiceName'
            serviceConnection: 'http://51.124.139.165:8080/api/v1/namespaces/default/deployments/4ebe37b7-79af-40a2-a0d5-05976f062e52'
            method: 'PATCH'
            headers: |
              {
              "Content-Type":"application/yaml", 
              }
            body: |
              kind: Deployment
              apiVersion: v1
              spec:
                state: CANCELLED

