trigger:
- master


variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'cae00c10-93d7-4cb0-b141-9d475c70051c'

  # Agent VM image name
  vmImageName: 'windows-latest'

  # DEBUG
  system.debug: true


stages:

- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackage
    displayName: Maven Package
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      inputs:
        contents: 'target/learnflink-*.jar'
        targetFolder: '$(Pipeline.Workspace)' 

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)' 
        artifactName: JobJar


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: DownloadDeploy
      displayName: 'Download & Deploy'
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Pipeline Artifacts'
        inputs:
          artifact: 'JobJar'
          downloadPath: '$(Pipeline.Workspace)' 

      - task: AzureFileCopy@3
        inputs:
          sourcePath: '$(Pipeline.Workspace)' 
          azureSubscription: '$(azureSubscription)'
          destination: azureBlob
          storage: jqinblobstorage
          containerName: vvp

- stage: Run
  displayName: Run stage
  jobs:
    - job: Run
      steps:
        - script: echo Hello World

